env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
overrides:
  [
    {
      files: ['*.js'],
      rules: { 'space-before-function-paren': ['warn', 'ignore'] }
    }
  ]
