pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - author=snyk-bot
      - -conflict
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: false
