language: node_js
os: linux
node_js:
  - node
  - lts/*
  - 6
  - 8
  - 10
  - 12
jobs:
  include:
    - node_js: "13"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - sleep 15
  - mongo smallbusinessfridge --eval 'db.createUser({user:"testusr",pwd:"testpwd",roles:["readWrite"]});'
before_install:
  # Setup Node.js version-specific dependencies
  - |
    # mocha for testing
    # - use 3.x for Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm install --silent --save-dev mocha@3.5.3
    fi
  - |
    # supertest for http calls
    # - use 2.0.0 for Node.js < 4
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 4 ]]; then
      npm install --silent --save-dev supertest@2.0.0
    fi
  - |
    # Mocha lcov reporter for coverage
    npm install --save-dev mocha-lcov-reporter
  # Update Node.js modules
  - |
    # Prune and rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
script:
  # Run test script
  - npm run test
  # Run linting
  - |
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -eq "12.13.0" ]]; then
      npm run lint
    fi
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls
    coveralls < ./coverage/lcov.info
