# Call api to get scannerAuthUser
GET https://localhost/api/customerName?customer=1 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

POST https://localhost/api/keypadOrder HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

{
  "customer": 1,
  "product": 1
}

###

GET https://localhost/api/scannerAuthUser?customer=123456 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

GET https://localhost/api/scannerProduct?product=123 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

GET https://localhost/api/customerInsights?customer=00420123456789 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

GET https://localhost/api/customerInsights?customer=%2B420123456789 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

GET https://localhost/api/customerInsights?customer=00420 123 456 789 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

GET https://localhost/api/productList HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret

###

GET https://localhost/api/productList?voicebot=1 HTTP/1.1
Content-Type: application/json
sbf-API-secret: developmentsecret
