import type { HttpContext } from '@adonisjs/core/http'
import env from '#start/env'

/**
 * Web app manifest, served dynamically so an installed instance carries its own
 * APP_NAME and the visitor's locale. The icon set itself is generated by
 * `npm run generate:app-icons`.
 */
export default class ManifestController {
  async index({ i18n, response }: HttpContext) {
    const appName = env.get('APP_NAME', 'Small Business Fridge')

    response.header('content-type', 'application/manifest+json; charset=utf-8')
    response.header('cache-control', 'public, max-age=3600')

    return {
      id: '/',
      name: appName,
      short_name: appName,
      lang: i18n?.locale ?? 'cs',
      start_url: '/',
      scope: '/',
      display: 'standalone',
      background_color: '#09090b',
      theme_color: '#09090b',
      icons: [
        { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
        { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        {
          src: '/icon-maskable-512.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'maskable',
        },
      ],
    }
  }
}
