/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    Auth: () => import('#controllers/api/auth_controller'),
    Customers: () => import('#controllers/api/customers_controller'),
    Health: () => import('#controllers/api/health_controller'),
    Orders: () => import('#controllers/api/orders_controller'),
    Products: () => import('#controllers/api/products_controller'),
  },
  web: {
    admin: {
      Allergens: () => import('#controllers/web/admin/allergens_controller'),
      Audit: () => import('#controllers/web/admin/audit_controller'),
      Categories: () => import('#controllers/web/admin/categories_controller'),
      Dashboard: () => import('#controllers/web/admin/dashboard_controller'),
      Impersonation: () => import('#controllers/web/admin/impersonation_controller'),
      Invoices: () => import('#controllers/web/admin/invoices_controller'),
      MusicTracks: () => import('#controllers/web/admin/music_tracks_controller'),
      Orders: () => import('#controllers/web/admin/orders_controller'),
      Storno: () => import('#controllers/web/admin/storno_controller'),
      Users: () => import('#controllers/web/admin/users_controller'),
    },
    Audit: () => import('#controllers/web/audit_controller'),
    Home: () => import('#controllers/web/home_controller'),
    Invoices: () => import('#controllers/web/invoices_controller'),
    Kiosk: () => import('#controllers/web/kiosk_controller'),
    Login: () => import('#controllers/web/login_controller'),
    Oidc: () => import('#controllers/web/oidc_controller'),
    Orders: () => import('#controllers/web/orders_controller'),
    Profile: () => import('#controllers/web/profile_controller'),
    Shop: () => import('#controllers/web/shop_controller'),
    supplier: {
      Deliveries: () => import('#controllers/web/supplier/deliveries_controller'),
      Invoice: () => import('#controllers/web/supplier/invoice_controller'),
      Payments: () => import('#controllers/web/supplier/payments_controller'),
      Products: () => import('#controllers/web/supplier/products_controller'),
      Stock: () => import('#controllers/web/supplier/stock_controller'),
    },
  },
}
