services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: sbf
      POSTGRES_PASSWORD: sbf
      POSTGRES_DB: sbf
    volumes:
      - pgdata:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8083:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
  mailpit:
