/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AllergenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDisabled', 'name', 'updatedAt'] as const
  $columns = AllergenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDisabled: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'entityId', 'entityType', 'id', 'metadata', 'targetUserId', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare targetUserId: number | null
  @column()
  declare userId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'isDisabled', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDisabled: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeliverySchema extends BaseModel {
  static $columns = ['amountLeft', 'amountSupplied', 'createdAt', 'id', 'price', 'productId', 'supplierId', 'updatedAt'] as const
  $columns = DeliverySchema.$columns
  @column()
  declare amountLeft: number
  @column()
  declare amountSupplied: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare price: number
  @column()
  declare productId: number
  @column()
  declare supplierId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmailVerificationTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'tokenHash', 'updatedAt', 'usedAt', 'userId'] as const
  $columns = EmailVerificationTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class IbanChangeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'iban', 'id', 'tokenHash', 'updatedAt', 'usedAt', 'userId'] as const
  $columns = IbanChangeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare iban: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['autoReminderCount', 'buyerId', 'createdAt', 'id', 'isPaid', 'isPaymentRequested', 'manualReminderCount', 'supplierId', 'totalCost', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare autoReminderCount: number | null
  @column()
  declare buyerId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPaid: boolean | null
  @column()
  declare isPaymentRequested: boolean | null
  @column()
  declare manualReminderCount: number | null
  @column()
  declare supplierId: number
  @column()
  declare totalCost: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class KioskSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'userId'] as const
  $columns = KioskSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class MusicTrackSchema extends BaseModel {
  static $columns = ['accessLevel', 'createdAt', 'filePath', 'id', 'isDisabled', 'mimeType', 'name', 'updatedAt', 'uploadedByUserId'] as const
  $columns = MusicTrackSchema.$columns
  @column()
  declare accessLevel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filePath: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDisabled: boolean
  @column()
  declare mimeType: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedByUserId: number | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['buyerId', 'channel', 'createdAt', 'deliveryId', 'id', 'invoiceId', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column()
  declare buyerId: number
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliveryId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PageViewSchema extends BaseModel {
  static $columns = ['channel', 'createdAt', 'id', 'userId'] as const
  $columns = PageViewSchema.$columns
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'tokenHash', 'updatedAt', 'usedAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class ProductAllergenSchema extends BaseModel {
  static $columns = ['allergenId', 'id', 'productId'] as const
  $columns = ProductAllergenSchema.$columns
  @column()
  declare allergenId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number
}

export class ProductSchema extends BaseModel {
  static $columns = ['barcode', 'categoryId', 'createdAt', 'description', 'displayName', 'id', 'imagePath', 'keypadId', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare barcode: string | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string
  @column()
  declare keypadId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProfilePendingDraftSchema extends BaseModel {
  static $columns = ['createdAt', 'draftKey', 'expiresAt', 'id', 'payload', 'updatedAt', 'userId'] as const
  $columns = ProfilePendingDraftSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare draftKey: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class RecommendationSchema extends BaseModel {
  static $columns = ['createdAt', 'generatedAt', 'id', 'model', 'productId', 'rank', 'score', 'userId'] as const
  $columns = RecommendationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare generatedAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare productId: number
  @column()
  declare rank: number
  @column()
  declare score: number
  @column()
  declare userId: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserAuthIdentitySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastLoginAt', 'provider', 'providerEmail', 'providerEmailVerified', 'providerUserId', 'updatedAt', 'userId'] as const
  $columns = UserAuthIdentitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare provider: string
  @column()
  declare providerEmail: string | null
  @column()
  declare providerEmailVerified: boolean
  @column()
  declare providerUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class UserExcludedAllergenSchema extends BaseModel {
  static $columns = ['allergenId', 'userId'] as const
  $columns = UserExcludedAllergenSchema.$columns
  @column()
  declare allergenId: number
  @column()
  declare userId: number
}

export class UserFavoriteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'userId'] as const
  $columns = UserFavoriteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number
  @column()
  declare userId: number
}

export class UserInvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'acceptedUserId', 'createdAt', 'email', 'expiresAt', 'id', 'invitedByUserId', 'revokedAt', 'role', 'tokenHash', 'updatedAt'] as const
  $columns = UserInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare acceptedUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserId: number | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['anonymizedAt', 'cardId', 'colorMode', 'createdAt', 'disabledAt', 'displayName', 'email', 'emailVerifiedAt', 'iban', 'ibanVerifiedAt', 'id', 'isDisabled', 'isKiosk', 'isPremium', 'keypadDisabled', 'keypadId', 'password', 'pendingEmail', 'pendingIban', 'phone', 'role', 'sendDailyReport', 'sendMailOnPurchase', 'showAllProducts', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare anonymizedAt: DateTime | null
  @column()
  declare cardId: string | null
  @column()
  declare colorMode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare disabledAt: DateTime | null
  @column()
  declare displayName: string | null
  @column()
  declare email: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare iban: string | null
  @column.dateTime()
  declare ibanVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDisabled: boolean | null
  @column()
  declare isKiosk: boolean | null
  @column()
  declare isPremium: boolean
  @column()
  declare keypadDisabled: boolean | null
  @column()
  declare keypadId: number | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare pendingEmail: string | null
  @column()
  declare pendingIban: string | null
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column()
  declare sendDailyReport: boolean | null
  @column()
  declare sendMailOnPurchase: boolean | null
  @column()
  declare showAllProducts: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
