/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AllergenSchema extends BaseModel {
  static $columns = ['id', 'name', 'isDisabled', 'createdAt', 'updatedAt'] as const
  $columns = AllergenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare isDisabled: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['id', 'userId', 'action', 'entityType', 'entityId', 'targetUserId', 'metadata', 'createdAt'] as const
  $columns = AuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare action: string
  @column()
  declare entityType: string
  @column()
  declare entityId: number | null
  @column()
  declare targetUserId: number | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['id', 'name', 'color', 'isDisabled', 'createdAt', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare color: string
  @column()
  declare isDisabled: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeliverySchema extends BaseModel {
  static $columns = ['id', 'supplierId', 'productId', 'amountSupplied', 'amountLeft', 'price', 'createdAt', 'updatedAt'] as const
  $columns = DeliverySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare supplierId: number
  @column()
  declare productId: number
  @column()
  declare amountSupplied: number
  @column()
  declare amountLeft: number
  @column()
  declare price: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['id', 'buyerId', 'supplierId', 'totalCost', 'isPaid', 'isPaymentRequested', 'autoReminderCount', 'manualReminderCount', 'createdAt', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare buyerId: number
  @column()
  declare supplierId: number
  @column()
  declare totalCost: number
  @column()
  declare isPaid: boolean | null
  @column()
  declare isPaymentRequested: boolean | null
  @column()
  declare autoReminderCount: number | null
  @column()
  declare manualReminderCount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class KioskSessionSchema extends BaseModel {
  static $columns = ['id', 'userId', 'createdAt'] as const
  $columns = KioskSessionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class MusicTrackSchema extends BaseModel {
  static $columns = ['id', 'name', 'filePath', 'mimeType', 'accessLevel', 'isDisabled', 'uploadedByUserId', 'createdAt', 'updatedAt'] as const
  $columns = MusicTrackSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare filePath: string
  @column()
  declare mimeType: string
  @column()
  declare accessLevel: string
  @column()
  declare isDisabled: boolean
  @column()
  declare uploadedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderSchema extends BaseModel {
  static $columns = ['id', 'buyerId', 'deliveryId', 'invoiceId', 'channel', 'createdAt', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare buyerId: number
  @column()
  declare deliveryId: number
  @column()
  declare invoiceId: number | null
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PageViewSchema extends BaseModel {
  static $columns = ['id', 'userId', 'channel', 'createdAt'] as const
  $columns = PageViewSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['id', 'email', 'tokenHash', 'expiresAt', 'usedAt', 'createdAt', 'updatedAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare email: string
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAllergenSchema extends BaseModel {
  static $columns = ['id', 'productId', 'allergenId'] as const
  $columns = ProductAllergenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number
  @column()
  declare allergenId: number
}

export class ProductSchema extends BaseModel {
  static $columns = ['id', 'keypadId', 'displayName', 'description', 'imagePath', 'categoryId', 'barcode', 'createdAt', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keypadId: number
  @column()
  declare displayName: string
  @column()
  declare description: string
  @column()
  declare imagePath: string
  @column()
  declare categoryId: number | null
  @column()
  declare barcode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RecommendationSchema extends BaseModel {
  static $columns = ['id', 'userId', 'productId', 'score', 'model', 'rank', 'generatedAt', 'createdAt'] as const
  $columns = RecommendationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare productId: number
  @column()
  declare score: number
  @column()
  declare model: string
  @column()
  declare rank: number
  @column.dateTime()
  declare generatedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'hash', 'createdAt', 'updatedAt', 'expiresAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare hash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
}

export class UserExcludedAllergenSchema extends BaseModel {
  static $columns = ['userId', 'allergenId'] as const
  $columns = UserExcludedAllergenSchema.$columns
  @column()
  declare userId: number
  @column()
  declare allergenId: number
}

export class UserFavoriteSchema extends BaseModel {
  static $columns = ['id', 'userId', 'productId', 'createdAt'] as const
  $columns = UserFavoriteSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare productId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class UserInvitationSchema extends BaseModel {
  static $columns = ['id', 'email', 'role', 'tokenHash', 'invitedByUserId', 'acceptedUserId', 'expiresAt', 'acceptedAt', 'revokedAt', 'createdAt', 'updatedAt'] as const
  $columns = UserInvitationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare email: string
  @column()
  declare role: string
  @column()
  declare tokenHash: string
  @column()
  declare invitedByUserId: number | null
  @column()
  declare acceptedUserId: number | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'oid', 'password', 'displayName', 'email', 'phone', 'iban', 'keypadId', 'cardId', 'role', 'isKiosk', 'isDisabled', 'showAllProducts', 'sendMailOnPurchase', 'sendDailyReport', 'colorMode', 'keypadDisabled', 'createdAt', 'updatedAt', 'isPremium'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare oid: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare displayName: string | null
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare iban: string | null
  @column()
  declare keypadId: number
  @column()
  declare cardId: string | null
  @column()
  declare role: string
  @column()
  declare isKiosk: boolean | null
  @column()
  declare isDisabled: boolean | null
  @column()
  declare showAllProducts: boolean | null
  @column()
  declare sendMailOnPurchase: boolean | null
  @column()
  declare sendDailyReport: boolean | null
  @column()
  declare colorMode: string | null
  @column()
  declare keypadDisabled: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare isPremium: boolean
}
