name: Build and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      run: EPOCH=$(date +%s) && docker build . --file Dockerfile --tag houbystudio/small-business-fridge:$EPOCH --tag houbystudio/small-business-fridge:latest && docker push --all-tags houbystudio/small-business-fridge
